Giocomo sbx imaging datainterfaces
catalystneuro/nwb-conversion-tools pull request #133
Opened 2021-02-05 13:07 UTC by Saksham20

adds 
1) Interface for the Giocomo labs Plitt VR data.
2) Creates a NWBConverter child class for the complete conversion

2021-02-05 13:11 UTC, Saksham20 commented
will pass when #132 merges

2021-02-08 16:57 UTC, bendichter requested changes
these changes are in the wrong repo

2021-02-08 16:57 UTC, bendichter commented on nwb_conversion_tools/datainterfaces/giocomoconverter.py
> +from .giocomovrdatainterface import GiocomoVRInterface
The Giocomo converter should go in [giocomo-lab-to-nwb](https://github.com/catalystneuro/giocomo-lab-to-nwb)

2021-02-08 16:57 UTC, bendichter commented on nwb_conversion_tools/datainterfaces/giocomoconverter.py
> +class GiocomoImagingInterface(NWBConverter):
Anything "Giocomo" should go in https://github.com/catalystneuro/giocomo-lab-to-nwb

2021-02-08 16:58 UTC, bendichter commented
@Saksham20 please make sure that all lab-specific converters and interfaces are added to the lab repo, not NWB Conversion Tools. SBXDataInterface goes in this repo, but GiocomoNWBConverter and all Giocomo-specific interfaces do not

2021-02-08 16:58 UTC, closed without merging