update all ecephys interface channel properties
catalystneuro/nwb-conversion-tools pull request #195
Opened 2021-06-14 17:57 UTC by CodyCBakerPhD

Adaptation to [PR #181](https://github.com/catalystneuro/nwb-conversion-tools/pull/181). I wrote this stuff a while back in anticipation of the changes, but a lot has changed since then so I'll just open it as a draft and update once #181 is through.

## Motivation

Sakhsham's new `add_electrode` method clarifies the boundary of heavy vs. light metadata for electrode tables. All data values that match to electrode columns are now set as channel properties in the `RecordingExtractor` object, while text descriptions are still passed along the usual global `metadata` object.

## How to test the behavior?
```
# TODO
```

## Checklist

- [X] Have you checked our [Contributing](https://github.com/catalystneuro/nwb-conversion-tools/blob/master/docs/contribute.rst) document?
- [X] Have you ensured the PR description clearly describes problem and the solution?
- [X] Is your contribution compliant with our coding style? Read about [PEP8](https://www.python.org/dev/peps/pep-0008/) and [black](https://black.readthedocs.io/en/stable/the_black_code_style.html).
- [X] Have you checked to ensure that there aren't other open or previously closed [Pull Requests](https://github.com/catalystneuro/nwb-conversion-tools/pulls) for the same change? (shares some similarity with #181 for certain interfaces)
- [X] Have you included the relevant issue number using `#XXX` notation where `XXX` is the issue number?

2021-06-16 16:47 UTC, CodyCBakerPhD commented
@luiztauffer @sbuergers Take a look if you get a second - host of updates to various interfaces y'all use with respect to the new electrodes method, feel free to modify as needed

2021-06-23 13:23 UTC, Saksham20 requested changes

2021-06-23 13:23 UTC, Saksham20 commented on nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
>                      )
```suggestion
```

2021-06-23 13:23 UTC, Saksham20 commented on nwb_conversion_tools/datainterfaces/ecephys/openephys/openephysdatainterface.py
> +
```suggestion
```

2021-06-23 13:23 UTC, Saksham20 commented on nwb_conversion_tools/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
> +            )
```suggestion
```

2021-08-05 19:07 UTC, CodyCBakerPhD commented
Attempting to update master into this results in as many conflicts as there are changes - would just be easier to reopen under different branch. I'll try to get around to this soon

2021-08-05 19:07 UTC, closed without merging