added spikegadgets data interface with new source_schema setting method
catalystneuro/nwb-conversion-tools pull request #215
Opened 2021-07-20 20:15 UTC by CodyCBakerPhD

## Motivation
SpikeGadgetsRawIO has been merged to neo master ([PR #954](https://github.com/NeuralEnsemble/python-neo/pull/954)), and SpikeGadgetsRecordingExtractor has been merged to spikeextractors master ([PR #592](https://github.com/SpikeInterface/spikeextractors/pull/592)).

This is the next step of building the `SpikeGadgetsDataInterface`. Pretty simple, doesn't require a lot of extra setting in terms of metadata, aside from the optional probe file.

## How to test the behavior?
Existing schema tests should cover the new interface since it was added to the `interface_list`.

Other than that, a big to-do for this and all the other data interfaces is to add GIN and other running tests to ensure they function as expected.

## Checklist

- [X] Have you checked our [Contributing](https://github.com/catalystneuro/nwb-conversion-tools/blob/master/docs/contribute.rst) document?
- [X] Have you ensured the PR description clearly describes the problem and solutions?
- [X] Is your contribution compliant with our coding style? Read about [PEP8](https://www.python.org/dev/peps/pep-0008/) and [black](https://black.readthedocs.io/en/stable/the_black_code_style.html).
- [X] Have you checked to ensure that there aren't other open or previously closed [Pull Requests](https://github.com/catalystneuro/nwb-conversion-tools/pulls) for the same change?

2021-07-20 20:18 UTC, CodyCBakerPhD commented
@luiztauffer We'll certainly get a better look once the other CI workflow PR is merged, but right now the AxonaPositionInterface is causing new issue with some annotations, any clue why?

Also interesting to note that when I run the tests locally on Windows, I see similar issues with the Hdf5 and Tiff Imaging interfaces...

2021-07-20 22:01 UTC, bendichter requested changes
Looks good. Are we able to create tests for this as well?

2021-07-20 22:03 UTC, bendichter commented on nwb_conversion_tools/datainterfaces/ecephys/spikegadgets/spikegadgetsdatainterface.py
> +    def __init__(self, filename: PathType, probe_file_path: OptionalPathType):
```suggestion
    def __init__(self, filename: PathType, probe_file_path: OptionalPathType = None):
```

2021-07-20 23:15 UTC, CodyCBakerPhD commented on nwb_conversion_tools/datainterfaces/ecephys/spikegadgets/spikegadgetsdatainterface.py
> +        self.recording_extractor = load_probe_file(recording=self.recording_extractor, probe_file=probe_file_path)
Whoops... adding now

2021-07-20 23:18 UTC, CodyCBakerPhD commented
@bendichter When I add the GIN tests in their entirety, the writing of actual spikegadgets data (a part of which is using data from the Brody lab itself) will be among the formats covered.

I'll try to get that up later this week.

2021-07-22 13:17 UTC, luiztauffer commented
@CodyCBakerPhD 
I removed an unnecessary argument from the `AxonaPositionDataInterface.run_conversion()` method and this solved the previous error.
Right now we have the CI passing for the development env, but not for the production env.

2021-07-22 13:19 UTC, luiztauffer approved these changes

2021-07-22 16:08 UTC, CodyCBakerPhD commented
@luiztauffer Cool, that's to be expected pending the next neo/se releases. The production testing may have also revealed some new version dependence issues we can work through in a subsequent PR. Merging for now so we can get this dev fix in at least

2021-07-22 16:08 UTC, merged